###

GET http://localhost:8080/api/users

### Crear estudiante

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "nicmango",
    "password": "admin123",
    "fullName": "Nicolas Manjarres",
    "email": "nmanja@devsenior.es",
    "phone": "12345678",
    "intereses": ["Programación, juegos, futbol"],
    "profile": "Student",
    "school": "Ibero",
    "program": "Ing de Software"
}

### Crear Profesor

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "dmedina",
    "password": "admin123",
    "fullName": "Dayana Medina",
    "email": "dmedi@devsenior.es",
    "phone": "12345678",
    "intereses": ["Programación, Moda, Viajes"],
    "profile": "Employee",
    "company": "Ibero",
    "position": "CEO",
    "seniority": "Senior"
}